### ISSUE TITLE
Feature request: change font in obs-textml

### ISSUE THREAD

**Issue by chrissv** [dcmouser/obsPlugins#1]
Just discovered obs-textml and it works great for my needs! I found the documentation the in-line modifiers such as [F+10]
One thing which would be helpful to me would be to add the ability to change the actual font face via the [ ] nomenclature. It would override the font specified in the dialog box.

I want to have a single text box with different fonts per line.

Thoughts?
Thanks!

**Comment by dcmouser** [comment]
I have pushed out a new version with this option :)
